import Head from 'next/head'
import Home from "./home"
import Image from 'next/image'
import styles from '@/styles/Home.module.css'


export default function Index() {
  return (
    <div className="bg-teal-600">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <h1>Organik Ürünler</h1>
      </Head>
      <Home/>
    </div>
  )
}
