import Head from 'next/head'
import Home from "./home"
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Header'


export default function Index() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
       
      </Head>
      <Header/>
      <Home />
     
    </div>
  )
}
